lints = [
  { name = "nix fmt", command = "ci-nix-fmt" },
  { name = "ci fmt", command = "ci-fmt" },
  { name = "ci clippy", command = "ci-clippy" },
  { name = "ci test", command = "ci-test" },
  { name = "cargo machete", command = "ci-machete" },
  { name = "cargo sort", command = "ci-sort" },
  { name = "cargo deny", command = "ci-deny" },
  { name = "cargo audit", command = "ci-audit" },
]
